### ISSUE TITLE
Error with the statuses list for the flyer

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/sirepo-bluesky#23]
Noticed in the [build log](https://dev.azure.com/nsls2/profile_collections/_build/results?buildId=2074&view=logs&j=8d99ad36-e016-5305-6a8b-ec3199d20735&t=fdef6bdd-c258-506f-09a8-681d9ef2fd71) for https://github.com/NSLS-II-TES/profile_sirepo/pull/4:
```py
[I 2021-05-14 23:43:49,365.365 TerminalIPythonApp  shellapp:367] Running file in user namespace: /home/vsts/work/1/s/startup/20-flyer-environment.py
[I 2021-05-14 23:43:49,464.464 TerminalIPythonApp  shellapp:367] Running file in user namespace: /home/vsts/work/1/s/startup/92-optimization.py
[I 2021-05-14 23:43:49,785.785 TerminalIPythonApp  shellapp:367] Running file in user namespace: /home/vsts/work/1/s/.ci/drop-in.py
[I 2021-05-14 23:43:49,787.787 bluesky  run_engine:793] Executing plan <generator object optimization_plan at 0x7f4715f43bd0>
[I 2021-05-14 23:43:49,789.789 bluesky.RE.state  run_engine:121] Change state on <bluesky.run_engine.RunEngine object at 0x7f4729932450> from 'idle' -> 'running'
[E 2021-05-15 00:03:42,839.839 bluesky  run_engine:1499] Run aborted
Traceback (most recent call last):
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bluesky/run_engine.py", line 1342, in _run
    stashed_exception or resp)
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bloptools/de_optimization.py", line 518, in optimization_plan
    run_parallel=run_parallel))
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bloptools/de_opt_utils.py", line 127, in _run_flyers
    uid = (yield from bp.fly(flyer))
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bluesky/plans.py", line 1963, in fly
    yield from bps.collect(flyer)
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 656, in collect
    return (yield Msg('collect', obj, stream=stream, return_payload=return_payload))
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bluesky/run_engine.py", line 1425, in _run
    new_response = await coro(msg)
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bluesky/run_engine.py", line 1891, in _collect
    return (await current_run.collect(msg))
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bluesky/bundlers.py", line 673, in collect
    for ev in collect_obj.collect():
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/sirepo_bluesky/sirepo_flyer.py", line 352, in collect
    f'{self.name}_status': statuses[i],
IndexError: list index out of range
[I 2021-05-15 00:03:42,854.854 bluesky.RE.state  run_engine:121] Change state on <bluesky.run_engine.RunEngine object at 0x7f4729932450> from 'running' -> 'idle'
[E 2021-05-15 00:03:42,866.866 nslsii.ipython  logutils:56] list index out of range
Traceback (most recent call last):
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-19fca0ca65e8>", line 13, in <module>
    ip.parent._exec_file(f)
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/IPython/core/shellapp.py", line 380, in _exec_file
    raise_exceptions=True)
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2742, in safe_execfile
    self.compile if shell_futures else None)
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/IPython/utils/py3compat.py", line 168, in execfile
    for ev in collect_obj.collect():
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/sirepo_bluesky/sirepo_flyer.py", line 352, in collect
    f'{self.name}_status': statuses[i],
IndexError: list index out of range
```

**Comment by mrakitin** [comment]
@AbbyGi, have you seen that issue recently? Is it reproducible? Maybe we can add a test that would cover it.

**Comment by AbbyGi** [comment]
@mrakitin, I haven't seen it, but I also haven't used the flyer in a while or gotten around to trying to reproduce this error. +1 for adding more tests to check the flyer, though.

**Comment by mrakitin** [comment]
@thomaswmorris started using flyers, so we'll keep this issue open for now to see if there are similar issues happening.

**Comment by mrakitin** [comment]
Does not seem like a problem. We can always reopen this issue or open a new one if we encounter such a problem.
