### ISSUE TITLE
AssertionError: download-data-file/srw/GK7PEi1e/watchpointReport7/-1 request failed, status: 404

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/sirepo-bluesky#25]
Another error observed during the [build](https://dev.azure.com/nsls2/profile_collections/_build/results?buildId=2078&view=logs&j=8d99ad36-e016-5305-6a8b-ec3199d20735&t=48dd66e2-de3e-510e-9f8f-743bb21e5f0a) for https://github.com/NSLS-II-TES/profile_sirepo/pull/4.

```py
[I 2021-05-15 00:28:17,131.131 TerminalIPythonApp  shellapp:367] Running file in user namespace: /home/vsts/work/1/s/startup/20-flyer-environment.py
[I 2021-05-15 00:28:17,249.249 TerminalIPythonApp  shellapp:367] Running file in user namespace: /home/vsts/work/1/s/startup/92-optimization.py
[I 2021-05-15 00:28:17,586.586 TerminalIPythonApp  shellapp:367] Running file in user namespace: /home/vsts/work/1/s/.ci/drop-in.py
[I 2021-05-15 00:28:17,587.587 bluesky  run_engine:793] Executing plan <generator object optimization_plan at 0x7f0e0d83a9d0>
[I 2021-05-15 00:28:17,589.589 bluesky.RE.state  run_engine:121] Change state on <bluesky.run_engine.RunEngine object at 0x7f0e56b40650> from 'idle' -> 'running'
[E 2021-05-15 00:34:14,218.218 bluesky  run_engine:1499] Run aborted
Traceback (most recent call last):
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bluesky/run_engine.py", line 1342, in _run
    stashed_exception or resp)
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bloptools/de_optimization.py", line 518, in optimization_plan
    run_parallel=run_parallel))
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bloptools/de_opt_utils.py", line 127, in _run_flyers
    uid = (yield from bp.fly(flyer))
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bluesky/plans.py", line 1963, in fly
    yield from bps.collect(flyer)
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 656, in collect
    return (yield Msg('collect', obj, stream=stream, return_payload=return_payload))
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bluesky/run_engine.py", line 1425, in _run
    new_response = await coro(msg)
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bluesky/run_engine.py", line 1891, in _collect
    return (await current_run.collect(msg))
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/bluesky/bundlers.py", line 673, in collect
    for ev in collect_obj.collect():
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/sirepo_bluesky/sirepo_flyer.py", line 319, in collect
    data_file = self._copies[i].get_datafile()
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/sirepo_bluesky/sirepo_bluesky.py", line 125, in get_datafile
    self._assert_success(response, url)
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/sirepo_bluesky/sirepo_bluesky.py", line 173, in _assert_success
    '{} request failed, status: {}'.format(url, response.status_code)
AssertionError: download-data-file/srw/GK7PEi1e/watchpointReport7/-1 request failed, status: 404
[I 2021-05-15 00:34:14,295.295 bluesky.RE.state  run_engine:121] Change state on <bluesky.run_engine.RunEngine object at 0x7f0e56b40650> from 'running' -> 'idle'
[E 2021-05-15 00:34:14,298.298 nslsii.ipython  logutils:56] download-data-file/srw/GK7PEi1e/watchpointReport7/-1 request failed, status: 404
Traceback (most recent call last):
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-19fca0ca65e8>", line 13, in <module>
    ip.parent._exec_file(f)
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/IPython/core/shellapp.py", line 380, in _exec_file
    self._assert_success(response, url)
  File "/home/vsts/miniconda/envs/collection-2021-1.0/lib/python3.7/site-packages/sirepo_bluesky/sirepo_bluesky.py", line 173, in _assert_success
    '{} request failed, status: {}'.format(url, response.status_code)
AssertionError: download-data-file/srw/GK7PEi1e/watchpointReport7/-1 request failed, status: 404
```

**Comment by mrakitin** [comment]
@moellep, I am not sure where that should be resolved - on the Sirepo side, or on this library's side?
