### ISSUE TITLE
Error happens with thousands of sirepo simulations

### ISSUE THREAD

**Issue by magiconline** [NSLS-II/sirepo-bluesky#77]
I'm using reinforcement learning and sirepo-bluesky. My plan triggered thousands of sirepo simulations. Sometimes the server not respond(or return nothing) and Bluesky RunEngine doesn't deal with that situation. Then RE and plan crushed. I can use try...except... outside RE, but I think Sirepo-Bluesky should handle that situation.

**Comment by mrakitin** [comment]
Thanks for your report. Do you have the specific error you observed in the server log? If the server does not return the expected data, we could try rerunning that simulation (implemented in the `trigger` method).

Also, it would be great to know what plan you are running, and what parameters are being varied. There is a chance the combination of parameters is unphysical or they cause the simulation to last too long so that you don't get the result in a reasonable amount of time.

Could you please try to reproduce it, and try running the same simulation via the Sirepo web interface to see if it's repeatable? Thanks.

**Comment by magiconline** [comment]
This is the log on the server:
```
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_api.py:94:api_downloadDataFile frame=-1 not found P5blxFxP srw

/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/uri_router.py:231:_dispatch exception=404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. path=download-data-file/srw/P5blxFxP/watchpointReport16/-1 stack=Traceback (most recent call last):

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/uri_router.py", line 229, in _dispatch

    return call_api(route.func, kwargs)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/uri_router.py", line 86, in call_api

    r = sirepo.http_reply.gen_exception(e)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/http_reply.py", line 60, in gen_exception

    return _gen_exception_werkzeug(exc)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/http_reply.py", line 386, in _gen_exception_werkzeug

    raise exc

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/uri_router.py", line 77, in call_api

    r = flask.make_response(f(**kwargs) if kwargs else f())

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_api.py", line 94, in api_downloadDataFile

    'frame={} not found {id} {type}'.format(frame, **req)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/util.py", line 314, in raise_not_found

    _raise('NotFound', *args, **kwargs)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/util.py", line 409, in _raise

    raise getattr(werkzeug.exceptions, exc)()

werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.


Exception was printed at:


werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 885, in _bootstrap

    self._bootstrap_inner()

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 917, in _bootstrap_inner

    self.run()

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 865, in run

    self._target(*self._args, **self._kwargs)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 650, in process_request_thread

    self.finish_request(request, client_address)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 360, in finish_request

    self.RequestHandlerClass(request, client_address, self)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 720, in __init__

    self.handle()

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 347, in handle

    BaseHTTPRequestHandler.handle(self)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/server.py", line 426, in handle

    self.handle_one_request()

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 379, in handle_one_request

    self.run_wsgi()

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 324, in run_wsgi

    execute(self.server.app)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 313, in execute

    application_iter = app(environ, start_response)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 2091, in __call__

    return self.wsgi_app(environ, start_response)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app

    response = self.full_dispatch_request()

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request

    rv = self.dispatch_request()

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

172.17.0.1 - - [07/May/2022 22:30:00] "GET /download-data-file/srw/P5blxFxP/watchpointReport16/-1 HTTP/1.1" 404 -

/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:363:_kill_if_idle LocalDriver(a=TzjE k=sequential u=sn6V [])
```

This is the log from my code:
```
ERROR:bluesky:Run aborted
Traceback (most recent call last):
  File "/home/cz/miniconda3/envs/AIECS/lib/python3.9/site-packages/bluesky/run_engine.py", line 1489, in _run
    msg = self._plan_stack[-1].throw(
  File "/tmp/ipykernel_353/331650112.py", line 35, in rl_plan
    uid = yield from bps.trigger_and_read(detectors)
  File "/home/cz/miniconda3/envs/AIECS/lib/python3.9/site-packages/bluesky/plan_stubs.py", line 911, in trigger_and_read
    return (yield from rewindable_wrapper(inner_trigger_and_read(),
  File "/home/cz/miniconda3/envs/AIECS/lib/python3.9/site-packages/bluesky/preprocessors.py", line 693, in rewindable_wrapper
    return (yield from plan)
  File "/home/cz/miniconda3/envs/AIECS/lib/python3.9/site-packages/bluesky/plan_stubs.py", line 898, in inner_trigger_and_read
    yield from trigger(obj, group=grp)
  File "/home/cz/miniconda3/envs/AIECS/lib/python3.9/site-packages/bluesky/plan_stubs.py", line 427, in trigger
    ret = yield Msg('trigger', obj, group=group)
  File "/home/cz/miniconda3/envs/AIECS/lib/python3.9/site-packages/bluesky/run_engine.py", line 1573, in _run
    new_response = await coro(msg)
  File "/home/cz/miniconda3/envs/AIECS/lib/python3.9/site-packages/bluesky/run_engine.py", line 2106, in _trigger
    ret = msg.obj.trigger(*msg.args, **kwargs)
  File "/home/cz/AIECS/sirepo-bluesky/sirepo_bluesky/sirepo_ophyd.py", line 128, in trigger
    datafile = self.connection.get_datafile()
  File "/home/cz/AIECS/sirepo-bluesky/sirepo_bluesky/sirepo_bluesky.py", line 134, in get_datafile
    self._assert_success(response, url)
  File "/home/cz/AIECS/sirepo-bluesky/sirepo_bluesky/sirepo_bluesky.py", line 188, in _assert_success
    assert response.status_code == requests.codes.ok,\
AssertionError: download-data-file/srw/P5blxFxP/watchpointReport16/-1 request failed, status: 404
INFO:bluesky.RE.state:Change state on <bluesky.run_engine.RunEngine object at 0x7fa56a3cffa0> from 'running' -> 'idle'
```

It seems the sim_id I have been using has changed or disappear on the server. I'm sure I'm using the same sim_id. And if I run my code again that sim_id is OK.

**Comment by magiconline** [comment]
This is another error on the server:

```
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_api.py:244:_request api=api_runStatus runDir=/sirepo/user/sn6VnGV5/srw/P5blxFxP/watchpointReport16

/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/uri_router.py:85:call_api api=<function api_runStatus at 0x7fd1c2040598> exception=('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) stack=Traceback (most recent call last):

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen

    chunked=chunked,

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request

    conn.request(method, url, **httplib_request_kw)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connection.py", line 239, in request

    super(HTTPConnection, self).request(method, url, body=body, headers=headers)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1229, in request

    self._send_request(method, url, body, headers, encode_chunked)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1275, in _send_request

    self.endheaders(body, encode_chunked=encode_chunked)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1224, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1055, in _send_output

    self.send(chunk)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 977, in send

    self.sock.sendall(data)

ConnectionResetError: [Errno 104] Connection reset by peer


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/adapters.py", line 450, in send

    timeout=timeout

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen

    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/util/retry.py", line 550, in increment

    raise six.reraise(type(error), error, _stacktrace)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/packages/six.py", line 769, in reraise

    raise value.with_traceback(tb)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen

    chunked=chunked,

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request

    conn.request(method, url, **httplib_request_kw)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connection.py", line 239, in request

    super(HTTPConnection, self).request(method, url, body=body, headers=headers)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1229, in request

    self._send_request(method, url, body, headers, encode_chunked)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1275, in _send_request

    self.endheaders(body, encode_chunked=encode_chunked)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1224, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1055, in _send_output

    self.send(chunk)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 977, in send

    self.sock.sendall(data)

urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/uri_router.py", line 77, in call_api

    r = flask.make_response(f(**kwargs) if kwargs else f())

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_api.py", line 180, in api_runStatus

    return _request()

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_api.py", line 249, in _request

    verify=sirepo.job.cfg.verify_tls,

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/api.py", line 117, in post

    return request('post', url, data=data, json=json, **kwargs)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/api.py", line 61, in request

    return session.request(method=method, url=url, **kwargs)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/sessions.py", line 529, in request

    resp = self.send(prep, **send_kwargs)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/sessions.py", line 645, in send

    r = adapter.send(request, **kwargs)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/adapters.py", line 501, in send

    raise ConnectionError(err, request=request)

requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))


Exception was printed at:


requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 885, in _bootstrap

    self._bootstrap_inner()

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 917, in _bootstrap_inner

    self.run()

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 865, in run

    self._target(*self._args, **self._kwargs)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 650, in process_request_thread

    self.finish_request(request, client_address)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 360, in finish_request

    self.RequestHandlerClass(request, client_address, self)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 720, in __init__

    self.handle()

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 347, in handle

    BaseHTTPRequestHandler.handle(self)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/server.py", line 426, in handle

    self.handle_one_request()

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 379, in handle_one_request

    self.run_wsgi()

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 324, in run_wsgi

    execute(self.server.app)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 313, in execute

    application_iter = app(environ, start_response)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 2091, in __call__

    return self.wsgi_app(environ, start_response)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app

    response = self.full_dispatch_request()

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request

    rv = self.dispatch_request()

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/uri_router.py", line 229, in _dispatch

    return call_api(route.func, kwargs)

/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/http_reply.py:285:_gen_exception_error unsupported exception=<class 'requests.exceptions.ConnectionError'> msg=('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/uri_router.py:231:_dispatch exception=500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application. path=run-status stack=Traceback (most recent call last):

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen

    chunked=chunked,

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request

    conn.request(method, url, **httplib_request_kw)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connection.py", line 239, in request

    super(HTTPConnection, self).request(method, url, body=body, headers=headers)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1229, in request

    self._send_request(method, url, body, headers, encode_chunked)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1275, in _send_request

    self.endheaders(body, encode_chunked=encode_chunked)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1224, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1055, in _send_output

    self.send(chunk)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 977, in send

    self.sock.sendall(data)

ConnectionResetError: [Errno 104] Connection reset by peer


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/adapters.py", line 450, in send

    timeout=timeout

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen

    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/util/retry.py", line 550, in increment

    raise six.reraise(type(error), error, _stacktrace)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/packages/six.py", line 769, in reraise

    raise value.with_traceback(tb)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen

    chunked=chunked,

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request

    conn.request(method, url, **httplib_request_kw)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/urllib3/connection.py", line 239, in request

    super(HTTPConnection, self).request(method, url, body=body, headers=headers)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1229, in request

    self._send_request(method, url, body, headers, encode_chunked)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1275, in _send_request

    self.endheaders(body, encode_chunked=encode_chunked)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1224, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 1055, in _send_output

    self.send(chunk)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/client.py", line 977, in send

    self.sock.sendall(data)

urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/uri_router.py", line 77, in call_api

    r = flask.make_response(f(**kwargs) if kwargs else f())

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_api.py", line 180, in api_runStatus

    return _request()

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_api.py", line 249, in _request

    verify=sirepo.job.cfg.verify_tls,

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/api.py", line 117, in post

    return request('post', url, data=data, json=json, **kwargs)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/api.py", line 61, in request

    return session.request(method=method, url=url, **kwargs)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/sessions.py", line 529, in request

    resp = self.send(prep, **send_kwargs)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/sessions.py", line 645, in send

    r = adapter.send(request, **kwargs)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/requests/adapters.py", line 501, in send

    raise ConnectionError(err, request=request)

requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/uri_router.py", line 229, in _dispatch

    return call_api(route.func, kwargs)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/uri_router.py", line 86, in call_api

    r = sirepo.http_reply.gen_exception(e)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/http_reply.py", line 61, in gen_exception

    return _gen_exception_error(exc)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/http_reply.py", line 287, in _gen_exception_error

    raise werkzeug.exceptions.InternalServerError()

werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.


Exception was printed at:


werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 885, in _bootstrap

    self._bootstrap_inner()

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 917, in _bootstrap_inner

    self.run()

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 865, in run

    self._target(*self._args, **self._kwargs)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 650, in process_request_thread

    self.finish_request(request, client_address)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 360, in finish_request

    self.RequestHandlerClass(request, client_address, self)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/socketserver.py", line 720, in __init__

    self.handle()

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 347, in handle

    BaseHTTPRequestHandler.handle(self)

  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/http/server.py", line 426, in handle

    self.handle_one_request()

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 379, in handle_one_request

    self.run_wsgi()

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 324, in run_wsgi

    execute(self.server.app)

  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/werkzeug/serving.py", line 313, in execute

    application_iter = app(environ, start_response)<SNIP>

172.17.0.1 - - [08/May/2022 05:28:01] "POST /run-status HTTP/1.1" 500 -

/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/sirepo/job_driver/__init__.py:303:_receive LocalDriver(a=TzjE k=sequential u=sn6V [_Op(run, bXdB)]) opName=run o=bXdB
```

**Comment by mrakitin** [comment]
@magiconline, thanks for the logs, however, with this information, it's hard to reproduce your issue.

Can you please provide us a snippet of code that you've used to run the scans/simulations, along with the simulation archive, which can be exported from the web frontend of Sirepo as a .zip archive?

With that information, our team can try to reproduce the issue with your input data, and try to develop a workaround.

**Comment by mrakitin** [comment]
If you already have a local fix, we absolutely love external contributions, so please feel free to open a pull request.

**Comment by mrakitin** [comment]
We did not receive enough details about the issue. Closing. Feel free to reopen with the requested details.
